name: Debug Windows Vcpkg
on:
  push:
    branches:
      - test-boost-vcpkg

jobs:
  debug-vcpkg:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Boost via Choco
        run: |
          choco install boost-msvc-14.3

      - name: Find Boost via Choco
        run: |
          dir /s /b C:\local\*config.hpp* | findstr boost

      - name: Set up BOOST_ROOT
        run: |
          $boost_dir = (Get-ChildItem "C:\local" -Filter "boost_*" | Select-Object -First 1).FullName
          echo "BOOST_ROOT=$boost_dir"

