name: Debug Windows Vcpkg
on:
  push:
    branches:
      - test-boost-vcpkg

jobs:
  debug-vcpkg:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Boost via Choco
        run: |
          choco install boost-msvc-14.3

      - name: Find Boost config.hpp via Choco
        run: |
          $paths = Get-ChildItem -Path C:\local -Filter "config.hpp" -Recurse -ErrorAction SilentlyContinue | Where-Object { $_.FullName -match "boost\\config\.hpp$" }
          foreach ($p in $paths) {
              Write-Output "FOUND BOOST CONFIG: $($p.FullName)"
          }

